# WHAT IS PYTORCH

## 参考资料



In [1]:
import torch
print(torch.__version__)

torch.random.seed()

1.5.0


1124275353873200

## 快速开始

### 张量


In [2]:
# 利用函数方法创建
x = torch.empty((2,3))
print(x)
x = torch.rand((2,3))
print(x)
x = torch.zeros((2,3), dtype=torch.long)
print(x)

tensor([[2.0544e+20, 2.1876e-04, 4.2002e-08],
        [1.6613e-07, 5.4890e-05, 2.1763e-04]])
tensor([[0.5808, 0.1049, 0.0565],
        [0.3225, 0.2916, 0.0933]])
tensor([[0, 0, 0],
        [0, 0, 0]])


In [3]:
# 利用数据创建
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [4]:
# 利用已有Tensor创建
x = x.new_ones((2,3), dtype=torch.double)      # new_* 方法保留Tensor形状
print(x)
x = torch.randn_like(x, dtype=torch.float)    # 设置数据类型
print(x)     

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.3179,  0.8589,  0.3080],
        [ 1.1617, -1.1464, -0.2248]])


In [5]:
print(x.size())   # Tensor形状
# or x.shape

torch.Size([2, 3])


### 操作

关于Tensor的更多操作详见 https://pytorch.org/docs/stable/torch.html  


In [6]:
x = torch.rand((2,3))
y = torch.ones((2,3))
print(x+y)
# or torch.add(x, y)
result = torch.empty((2,3))
torch.add(x, y, out=result)   # 指定输出的Tensor
print(result)

tensor([[1.7073, 1.1179, 1.5080],
        [1.3056, 1.9880, 1.8877]])
tensor([[1.7073, 1.1179, 1.5080],
        [1.3056, 1.9880, 1.8877]])


In [7]:
# 所有操作加上`_`后缀将成为改变原Tensor的操作
# 例如：x.opt_()会改变x本身，而x.opt()则不会
y.add(x)
print(y)
y.add_(x)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1.7073, 1.1179, 1.5080],
        [1.3056, 1.9880, 1.8877]])


In [8]:
# 可以使用类似NumPy的标准索引方式
print(x[:, 1])

tensor([0.1179, 0.9880])


In [9]:
# 使用`torch.view`改变Tensor形状
x = torch.randn(2, 3)
y = x.view(6)
z = x.view(-1, 2)  # 与np.reshape()同，指定为-1的轴将自动计算其size
print(x.size(), y.size(), z.size())

torch.Size([2, 3]) torch.Size([6]) torch.Size([3, 2])


In [10]:
# 对于单元素Tensor，使用`torch.item()`获取其数值
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0793])
0.07930459827184677


## NumPy 互转

`numpy.Array` 与 `torch.Tensor` 将共享底层存储，其一改变则一起改变  
注意，前提是 `torch.Tensor` 在CPU上，若在GPU上则不会  

### 转 NumPy.Array


In [12]:
a = torch.ones(5)
print(a, type(a))
b = a.numpy()
print(b, type(b))

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [13]:
# 共享底层存储
b[::2] = 0
print(a)    # a的数据改变
a.add_(1)
print(b)    # b的数据改变

tensor([0., 1., 0., 1., 0.])
[1. 2. 1. 2. 1.]


In [14]:
# 当a在GPU时不会共享底层存储，因为NumPy不支持GPU
# 或者说，a转移到GPU的操作是深拷贝
a = a.cuda()
b[::2] = 0
print(a)

tensor([1., 2., 1., 2., 1.], device='cuda:0')


### 转 Torch.Tensor


In [16]:
import numpy as np
print(np.__version__)

1.19.1


In [17]:
a = np.ones(5)
print(a, type(a))
b = torch.from_numpy(a)
print(b, type(b))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) <class 'torch.Tensor'>


In [18]:
# 共享底层存储
np.add(a, 1, out=a)
print(b)    # b的数据改变
b.add_(-1)
print(a)    # a的数据改变

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[1. 1. 1. 1. 1.]


## CUDA Tensors


In [23]:
device = torch.device("cuda:0") if torch.cuda.is_available() else torch.device("cpu")
print(device)

cuda:0


In [22]:
# 可以在创建Tensor时直接指定设备为GPU，也可以
# 在创建Tensor之后使用`torch.to()`或者`torch.cuda()`进行转换
x = torch.randn(2, 3)
y = torch.ones_like(x, device=device)
x = x.to(device)
z = x + y
print(z)
z = z.to('cpu', torch.double)
print(z)

tensor([[0.5936, 0.2140, 0.4248],
        [2.1912, 2.2343, 2.1905]], device='cuda:0')
tensor([[0.5936, 0.2140, 0.4248],
        [2.1912, 2.2343, 2.1905]], dtype=torch.float64)
